name: vietnam_map_flutter
description: Desktop Viet Nam map UI built with Flutter and Material 3.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.3.0
  vector_map_tiles: ^9.0.0-beta.8
  flutter_test:
    sdk: flutter
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  firebase_core: ^4.10.0
  cloud_firestore: ^6.5.0
  firebase_auth: ^6.5.2
  excel: ^4.0.6
  crypto: ^3.0.7
  url_launcher: ^6.3.2
  google_sign_in: 6.2.2

dev_dependencies:
  flutter_lints: ^5.0.0

dependency_overrides:
  path_provider_android: 2.2.23

flutter:
  uses-material-design: true
  assets:
    - lib/features/vietnam_map/assets/data/
    - lib/features/vietnam_map/assets/boundaries/
    - lib/features/vietnam_map/assets/offline_tiles/
    - assets/images/
