sonar.projectKey=SU26-PRM393_VietNam-Map-Flutter
sonar.organization=su26-prm393


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=VietNam-Map-Flutter
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/GeneratedPluginRegistrant.*
sonar.test.inclusions=**/*_test.dart
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=lib/main.dart,lib/models/**,lib/screens/admin_dashboard.dart,lib/screens/admin_shell.dart,lib/screens/campaign_management_screen.dart,lib/screens/profile_screen.dart,lib/screens/user_dashboard.dart,lib/screens/user_shell.dart,lib/screens/vietnam_map_screen.dart,lib/widgets/**,lib/services/auth_service.dart,lib/services/campaign_repository.dart,lib/services/location_repository.dart,lib/services/pdf_export_service.dart,lib/seed/**
sonar.cpd.exclusions=lib/screens/admin_dashboard.dart,lib/screens/admin_shell.dart,lib/screens/campaign_management_screen.dart,lib/screens/profile_screen.dart,lib/screens/user_dashboard.dart,lib/screens/user_shell.dart,lib/screens/vietnam_map_screen.dart,lib/widgets/campaign_control_panel.dart,lib/widgets/map_viewport.dart,lib/seed/**

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
