sonar.projectKey=SU26-PRM393_VietNam-Map-Flutter
sonar.organization=su26-prm393


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=VietNam-Map-Flutter
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/GeneratedPluginRegistrant.*
sonar.test.inclusions=**/*_test.dart
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=lib/main.dart,lib/features/vietnam_map/model/**,lib/features/vietnam_map/presentation/**,lib/features/vietnam_map/database/isar_service.dart,lib/features/vietnam_map/data/location_repository.dart

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
