// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'env_loader.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return macos;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhD0qyjXcTSi6vqir2zslVlM-7onwaE3w',
    appId: '1:327780601219:web:6ca0b06761c49a7c2e3ab6',
    messagingSenderId: '327780601219',
    projectId: 'vietmap-flutter',
    authDomain: 'vietmap-flutter.firebaseapp.com',
    storageBucket: 'vietmap-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXgAql-KzSmptcOcQQDKLtCGeVlU_vAzY',
    appId: '1:327780601219:android:7e9dec0299381a472e3ab6',
    messagingSenderId: '327780601219',
    projectId: 'vietmap-flutter',
    storageBucket: 'vietmap-flutter.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt4cAQU_s38Y_HOteG8tpsikpG0lnpGk0',
    appId: '1:327780601219:ios:a9e75f2c8bea477a2e3ab6',
    messagingSenderId: '327780601219',
    projectId: 'vietmap-flutter',
    storageBucket: 'vietmap-flutter.firebasestorage.app',
    iosBundleId: 'com.example.vietnamMapFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhD0qyjXcTSi6vqir2zslVlM-7onwaE3w',
    appId: '1:327780601219:web:43301bd3b17ed53e2e3ab6',
    messagingSenderId: '327780601219',
    projectId: 'vietmap-flutter',
    authDomain: 'vietmap-flutter.firebaseapp.com',
    storageBucket: 'vietmap-flutter.firebasestorage.app',
  );

  static String get googleClientId {
    const fromEnv = String.fromEnvironment('GOOGLE_CLIENT_ID');
    if (fromEnv.isNotEmpty) return fromEnv;
    return getEnvValue('GOOGLE_CLIENT_ID') ?? '';
  }

  static String get googleClientSecret {
    const fromEnv = String.fromEnvironment('GOOGLE_CLIENT_SECRET');
    if (fromEnv.isNotEmpty) return fromEnv;
    return getEnvValue('GOOGLE_CLIENT_SECRET') ?? '';
  }
}
